// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnbz07zrxD-SpW3ydwZIYyE8VAVgbMMQ',
    appId: '1:751651064432:web:967f59a509adf6795a82b5',
    messagingSenderId: '751651064432',
    projectId: 'wsp-bd-ad81b',
    authDomain: 'wsp-bd-ad81b.firebaseapp.com',
    storageBucket: 'wsp-bd-ad81b.firebasestorage.app',
    measurementId: 'G-3S2C1T81QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiC9ewGcpDRtEjLMJySbzvii3hlaMzEuE',
    appId: '1:751651064432:android:f2422d82826271dc5a82b5',
    messagingSenderId: '751651064432',
    projectId: 'wsp-bd-ad81b',
    storageBucket: 'wsp-bd-ad81b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCokd2Th4PGS7KHs3achtaydlCWBNLUJuM',
    appId: '1:751651064432:ios:9218e47e20e686265a82b5',
    messagingSenderId: '751651064432',
    projectId: 'wsp-bd-ad81b',
    storageBucket: 'wsp-bd-ad81b.firebasestorage.app',
    iosBundleId: 'com.example.wsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCokd2Th4PGS7KHs3achtaydlCWBNLUJuM',
    appId: '1:751651064432:ios:9218e47e20e686265a82b5',
    messagingSenderId: '751651064432',
    projectId: 'wsp-bd-ad81b',
    storageBucket: 'wsp-bd-ad81b.firebasestorage.app',
    iosBundleId: 'com.example.wsp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbnbz07zrxD-SpW3ydwZIYyE8VAVgbMMQ',
    appId: '1:751651064432:web:206da49b08221e9c5a82b5',
    messagingSenderId: '751651064432',
    projectId: 'wsp-bd-ad81b',
    authDomain: 'wsp-bd-ad81b.firebaseapp.com',
    storageBucket: 'wsp-bd-ad81b.firebasestorage.app',
    measurementId: 'G-0FX1WH2FGF',
  );
}
